site_name: Technical Writer task - Micha≈Ç Krawczyk
site_url: https://LevNikolayevichMyshkin.github.io/Pega_writer_assessment/
theme:
  name: material

use_directory_urls: false

markdown_extensions:
  - admonition
  - toc:
      permalink: "#"

nav:
  - index.md
  - Task 1. How to use a bike: bike.md
